# Generated by Django 4.2 on 2024-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobapplication_company_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="location",
            field=models.CharField(default="Remote", max_length=255),
        ),
    ]
